#### Vintage Pi TV configuration ####

# Log level, one of: critical, error, warning, info, debug, or trace
log-level = 'info'

# Directories to search for videos in.
# Must be a list of one or more strings OR dictionaries like { path = <path>, recurse = <bool>, ignore = <bool> }
search-dirs = [
    "/media/VintagePiTV/videos",  # A string sets { recurse = false, ignore = false }
    { path = "/media/VintagePiTV", ignore = true },  # Ignore folder
    { path = "/media", recurse = true}, # Recurse into directory
]

# Channel mode, one of
#   - random -- Channel ordering determined by random shuffling
#   - random-deterministic -- Just like random, shuffles consistently while number of videos files is unchanged
#   - alphabetical -- Ordering alphabetical according to name (default
#   - config-only -- Only select channels from matches as they appear in [[video]] list, otherwise completely ignore videos
#   - config-first-random -- Lowest channels in order they appear in [[video]] list below, otherwise random (as above)
#   - config-first-random-deterministic -- Lowest channels in order they appear in [[video]] list below, otherwise random-deterministic (as above)
#   - config-first-alphabetical -- Lowest channels in order they appear in [[video]] below, otherwise alphabetical (as above)
#
channel-mode = "alphabetical"
#channel-mode = "random-deterministic"

# One of letterbox, zoom, stretch
#   - letterbox -- Add black bars to sides of videos that don't match your screen's aspect ratio
#   - stretch -- Stretch video to fit screen exactly, possibly warping it in the process
#   - zoom -- Zoom into video so it fits, losing the top or bottom of videos that don't match your screen's aspect ratio
aspect-mode = "letterbox"

# Save place in file while browsing channels (doesn't persist on restart)
save-place-while-browsing = true

# Between 0-100 (rounded to nearest 5), or false for muted
starting-volume = 100

# Amount of static to play between videos. Set to 0 or false to disable
static-time = 3.5
static-time-between-channels = 0.5

# Display framerate on the on-screen display (OSD)
show-fps = false

# Always enable embedded subtitles for a file if this is set
subtitles-default-on = false

# The on-screen display (OSD) will always be on if this is set (shows channel only)
channel-osd-always-on = false

# Completely disable the OSD if this is set
disable-osd = false

# Apply a basic vintage CRT filter effect to videos (not applied to OSD). May cause frames to be dropped.
crt-filter = false

# Sould we provide visualizations for audio files?
audio-visualization = true

# Ratings must be in order least restricted to most restricted, eg. G first, X last
ratings = [
    { rating = "G", description = "General", color = "#36D399" },  # The first will be the default rating of videos
    { rating = "PG", description = "Parental Guidance" },  # Color is #FFFFFF if unspecified
    { rating = "R", description = "Restricted", color = "#FFEE00" },
    { rating = "X", description = "Adult", color = "#F87272" },  # The last will be the rating set on startup
]
# Or disable ratings altogether
#ratings = false

# Rating to start with (defaults to last in list above)
#starting-rating = "X"

# Set valid file extensions to sane defaults
valid-file-extensions = "defaults"
# Or or provide a list of extensions (without the period)
# valid-file-extensions = [ "mp4", "mkv", "mov", "avi" ]

# Margin of monitor in pixels, for overscan purposes
overscan-margins = { top = 0, right = 0, bottom = 0, left = 0 }

# Password for web app. False to allow open access
#web-password = "topsecret"
web-password = false

# Whether the power key shuts down the device or only exits.
# Values: true, false, "pi-only" (only reboots if running on a Raspberry Pi)
power-key-shutdown = "pi-only"

### MPV options ###
[mpv-options]

# WARNING: For advanced users only! Arguments converted the mpv.MPV(...) constructor in python-mpv
# See https://github.com/jaseg/python-mpv and https://mpv.io/manual/stable/ for more details

### Defaults (uncomment to change)
#ao = "alsa"          # audio output driver [https://mpv.io/manual/stable/#audio-output-drivers]
#vo = "gpu"           # video output driver [https://mpv.io/manual/stable/#video-output-drivers]
#hwdec = "auto-safe"
#profile = "sw-fast"
#gpu-context = "drm"
#fullscreen = true

### More relevant settings
#audio-device = "alsa/default:CARD=A"  # Which audio device to use. For options run: $ mpv --audio-device=help
                                       # Unless you changed 'ao' above, you'll want devices that start with 'alsa/...'
                                       # For example, to force HDMI audio: "alsa/default:CARD=vc4hdmi0" (your mileage may vary)
                                       # If you're using ALSA, you may want to use the command: $ alsamixer
                                       # to max out your device's hardware volume. Vintage Pi TV "softvol" volume (software volume).
#drm-connector = "HDMI-A-1"  # Which monitor to use [https://mpv.io/manual/stable/#video-output-drivers-drm-connector]
                             # For options, run: $ mpv --drm-connector=help
#drm-mode = "1920x1080"  # DRM mode, set custom resolution here [https://mpv.io/manual/stable/#video-output-drivers-drm-mode]
                         # Use "preferred", "highest", or for more options, run: $ mpv --drm-mode=help
#drm-mode = "1280x768@119.80"
#drm-mode = "35"

[keyboard]
enabled = true
# For a list of keys, run: $ python -c 'import evdev.ecodes as e; print("\n".join(k for k in dir(e) if k.startswith("KEY_")))'
down = "KEY_DOWN"
left = "KEY_LEFT"
mute = "KEY_0"
osd = "KEY_M"
pause = "KEY_P"
power = "KEY_ESC"
random = "KEY_ENTER"
ratings = "KEY_R"
rewind = "KEY_BACKSPACE"
right = "KEY_RIGHT"
up = "KEY_UP"
volume-down = "KEY_MINUS"
volume-up = "KEY_EQUAL"

[ir-remote]
enabled = false
# Below are for the Argon 40 remote https://argon40.com/products/argon-remote
#protocol = "nec"
#variant = "nec"
# Keys below here, keyboard needs to be enabled they need to _also_ be defined above
down = 0xD2
left = 0x99
mute = false
osd = 0x9D
pause = 0xCE
power = false
random = 0xCB
ratings = false  # Power button is 0x9C but needs to be deactivated
rewind = 0x90
right = 0xC1
up = 0xCA
volume-down = 0x81
volume-up = 0x80

[[video]]
filename = "color-bars.mkv"  # Required. Should match filename exactly, omitting the directory completely
name = "Color Bars"  # Custom name for file, if omitted/empty will be based on filename
# Optional keys below
enabled = true  # If false, any file with this name will be ignored
rating = "G"  # If false or invalid, will be assigned the default rating. Default is first rating in 'ratings' above.
subtitles = false  # true to enable subtitles embedded into the video (by default the first embedded subtitle track)
                   # A number selects the ID of an embedded subtitle track
                   # Or an absolute or relative path to subtitle file (usually <filename>.srt)

## Add more videos below you want to customize below

#[[video]]
#filename = "another.mp4"
#name = "Scary Video"
#rating = "R"
#subtitles = true
